name: muslimdaily
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+3

environment:
  sdk: ^3.5.0
#  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  quran:
  cupertino_icons:
  google_fonts:
  provider:
  dio:
  flutter_rating_bar:
  in_app_review: ^2.0.8
  flutter_screenutil:
  http:


  # Share
  share_plus: ^7.2.1

  # Widget
#  home_widget: ^0.8.1
  adhan:
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^19.5.0
  intl:
  flutter_svg:
  just_audio: ^0.10.5
  audio_session: ^0.1.19
  rxdart: ^0.28.0
  url_launcher:
  timezone: ^0.10.0
  hijri: ^3.0.0
  dropdown_button2: ^2.3.9
  connectivity_plus: ^7.0.0
  flutter_native_splash: ^2.3.5
  mvc_pattern: ^8.12.0
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  geocoding: ^2.1.0
  cached_network_image:
  dartz: ^0.10.1
  permission_handler:
  either_dart: ^1.0.0
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.6.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider:
#  awesome_notifications: ^0.9.3
  get_it: ^7.2.0
  get_storage:
  fluttertoast:
  lottie:
  drift_flutter: ^0.2.4
  shared_preferences: ^2.2.2
  flutter_onboarding_slider: ^1.0.11
  flutter_offline:
  carousel_slider: ^4.2.1
  another_flushbar: ^1.12.32

  shimmer: ^3.0.0
  flare_flutter: ^3.0.2
  gradient_icon: ^2.0.9
  reorderables: ^0.6.0
  collection: ^1.18.0
  percent_indicator: ^4.2.3
  infinite_scroll_pagination: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  gif_view: ^0.4.4
  carousel_slider_plus: ^7.0.0
  device_preview: ^1.1.0
  expandable: ^5.0.1
  badges: ^3.1.2
  dots_indicator: ^3.0.0
  geolocator: ^10.0.0
  flutter_compass: ^0.8.1
  vector_math:
  simple_animations: ^5.1.0
  redacted: ^1.0.12
  toggle_switch: ^2.3.0
  slide_to_act: ^2.0.2
  rate_my_app: ^2.3.2
  animate_do: ^3.3.4
  flutter_expandable_fab: ^2.5.2
  flutter_widget_from_html: ^0.16.0
  workmanager: ^0.9.0+3
  quran_library: ^2.3.1
#  quran_library:
#    git:
#      ref: main
#      url: https://github.com/alheekmahlib/quran_library.git
  table_calendar: ^3.0.2
  fl_chart:
  package_info_plus: ^9.0.0
  upgrader: ^12.3.0
  version: ^3.0.2
  disable_battery_optimization: ^1.1.2
  android_intent_plus: ^6.0.0
#  flutter_quran:
#  quran_library:
#    path: packges/quran_library-1.3.2
flutter_native_splash:
  android: true
  ios: true
  web: true
  fullscreen: true
  color: "#ffffff"
  android_gravity: center
  ios_content_mode: scaleAspectFill
  image: "assets/images/logoApp.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter pub run flutter_native_splash:create
  hive_generator: ^2.0.1
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/icons/
    - assets/athan/

  fonts:
    - family: maja
      fonts:
        - asset: assets/fonts/majalla.ttf
    - family: me_quran
      fonts:
        - asset: assets/fonts/quraan.ttf

    - family: me
      fonts:
        - asset: assets/fonts/KFGQPC.ttf
    - family: GT Sectra Fine
      fonts:
        - asset: assets/fonts/gt_fine/GT Sectra Fine Regular.ttf
    - family: cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf

    - family: othman
      fonts:
        - asset: assets/fonts/othmaini/Othmani.ttf
    - family: othmanV2
      fonts:
        - asset: assets/fonts/othmaini/UthmanicHafs_V20.ttf

flutter_launcher_icons:
  image_path: "assets/images/logoApp.png"
  image_path_android: "assets/images/logoApp.png"
  image_path_ios: "assets/images/logoApp.png"
  remove_alpha_ios: true
  background_color_ios: "#FFFFFF"

  android: "launcher_icon"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logoApp.png"

  ios: true
  remove_alpha_channel_ios: true
#  flutter pub run flutter_launcher_icons:main
