// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'app/features/hadith_books/data/models/ar_hadith_model.dart';
import 'app/features/hadith_books/data/models/bn_hadith_model.dart';
import 'app/features/hadith_books/data/models/book_obj_model.dart';
import 'app/features/hadith_books/data/models/collection_lang.dart';
import 'app/features/hadith_books/data/models/collection_model.dart';
import 'app/features/hadith_books/data/models/en_hadith_model.dart';
import 'app/features/hadith_books/data/models/ur_hadith_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 279906806387164845),
      name: 'ARHadithModel',
      lastPropertyId: const obx_int.IdUid(18, 3166976819811043225),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 308090632550918950),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6248316531813817742),
            name: 'volumeNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 1832237917893140662),
            name: 'bookNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 803618332101843976),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3936765749500617780),
            name: 'babNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5907711418236803640),
            name: 'babName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3004680247094765498),
            name: 'hadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 5041094930720209829),
            name: 'newHadithNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4934726501602388175),
            name: 'hadithText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5718976977445587845),
            name: 'bookID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4531541091694717497),
            name: 'ourHadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4823435362377864651),
            name: 'matchingEnglishURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 4346791896801893820),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 2198760820242582293),
            name: 'arabicURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 5182971317112312699),
            name: 'annotations',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(16, 1246123607181273238),
            name: 'grade1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(17, 1487962165292840969),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 6342382167519669521),
            relationTarget: 'Collection'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(18, 3166976819811043225),
            name: 'hadithTextWithoutDiacritics',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8709869443617042354),
      name: 'BNHadithModel',
      lastPropertyId: const obx_int.IdUid(15, 4125703545137366313),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8406156303125611767),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7551045496388558274),
            name: 'volumeNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2230323264260726178),
            name: 'bookNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 8825553637816053157),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1053036255942210082),
            name: 'babNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 521664577018521354),
            name: 'babName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 76789015037529942),
            name: 'hadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 6556710476613873858),
            name: 'hadithText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8794852536915019532),
            name: 'bookID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8397604408833653187),
            name: 'ourHadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 4265154669639850618),
            name: 'matchingArabicURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 5658607294238141841),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 1184180335016021758),
            name: 'banglaURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 7805768533518945919),
            name: 'grade1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 4125703545137366313),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 4971498861521242838),
            relationTarget: 'Collection')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 5200632843442917454),
      name: 'BookObjModel',
      lastPropertyId: const obx_int.IdUid(4, 6596269256394225382),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 4339671306646965302),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1525978708932302516),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 850224636501005459),
            name: 'bookNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6596269256394225382),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(3, 1728599716088070254),
            relationTarget: 'Collection')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 3862882145412864305),
      name: 'Collection',
      lastPropertyId: const obx_int.IdUid(10, 5878178263459309352),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3351701468179972026),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1743742573148081607),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 9019484933162478101),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4389744567892354202),
            name: 'arAndEnName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 2568122382472028937),
            name: 'hasBooks',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 5551359983930958214),
            name: 'hasChapters',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 1012457022741981591),
            name: 'translations',
            type: 30,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 549779655260751920),
            name: 'totalBooksCount',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 4197327532889092207),
            name: 'totalHadith',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 5878178263459309352),
            name: 'totalAvailableHadith',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[
        obx_int.ModelRelation(
            id: const obx_int.IdUid(1, 3457507236185273423),
            name: 'collectionLangs',
            targetId: const obx_int.IdUid(5, 6077604189860109243)),
        obx_int.ModelRelation(
            id: const obx_int.IdUid(2, 5276487986925670381),
            name: 'booksNames',
            targetId: const obx_int.IdUid(3, 5200632843442917454))
      ],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'arabicHadiths',
            srcEntity: 'ARHadithModel',
            srcField: 'collection'),
        obx_int.ModelBacklink(
            name: 'englishHadiths',
            srcEntity: 'ENHadithModel',
            srcField: 'collection'),
        obx_int.ModelBacklink(
            name: 'urduHadiths',
            srcEntity: 'URHadithModel',
            srcField: 'collection')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 6077604189860109243),
      name: 'CollectionLang',
      lastPropertyId: const obx_int.IdUid(5, 7825060036257079804),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6483106517141296570),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4531635674058848529),
            name: 'lang',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 2007654058726710656),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5886939531100803453),
            name: 'shortIntro',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7825060036257079804),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 8729684576287354248),
            relationTarget: 'Collection')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 7127724949284143783),
      name: 'ENHadithModel',
      lastPropertyId: const obx_int.IdUid(15, 8523950314044559969),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6086875890666809716),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2919682914578402692),
            name: 'volumeNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3149815874927767039),
            name: 'bookNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5525100661342440335),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4115133573102321537),
            name: 'babNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1201903048235003734),
            name: 'babName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 8380204405870327292),
            name: 'hadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 509121758986107150),
            name: 'hadithText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 7559061017828444862),
            name: 'bookID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8603001741871287685),
            name: 'ourHadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 5629129713163929394),
            name: 'matchingArabicURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 824573733183725350),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 9041430849009418653),
            name: 'englishURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 498675505122633752),
            name: 'grade1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 8523950314044559969),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 61468410210588549),
            relationTarget: 'Collection')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 4176367185372955030),
      name: 'URHadithModel',
      lastPropertyId: const obx_int.IdUid(15, 6934902539185632680),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6396577618240780222),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7381232341833070377),
            name: 'volumeNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7449383888060059025),
            name: 'bookNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 7238791092260744178),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 4430812325824057645),
            name: 'babNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 6134834131825049853),
            name: 'babName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3036458073246142114),
            name: 'hadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 2315305624794332463),
            name: 'hadithText',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 5922470877021424032),
            name: 'bookID',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 1715279799261881215),
            name: 'ourHadithNumber',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2569485564893474524),
            name: 'matchingArabicURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 4353370158645134702),
            name: 'lastUpdated',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(13, 202132956161442891),
            name: 'urduURN',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(14, 9150960667132365276),
            name: 'grade1',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(15, 6934902539185632680),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(6, 8557786350588478354),
            relationTarget: 'Collection')
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 4176367185372955030),
      lastIndexId: const obx_int.IdUid(6, 8557786350588478354),
      lastRelationId: const obx_int.IdUid(2, 5276487986925670381),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ARHadithModel: obx_int.EntityDefinition<ARHadithModel>(
        model: _entities[0],
        toOneRelations: (ARHadithModel object) => [object.collection],
        toManyRelations: (ARHadithModel object) => {},
        getId: (ARHadithModel object) => object.id,
        setId: (ARHadithModel object, int id) {
          object.id = id;
        },
        objectToFB: (ARHadithModel object, fb.Builder fbb) {
          final bookNameOffset = fbb.writeString(object.bookName);
          final babNumberOffset = fbb.writeString(object.babNumber);
          final babNameOffset =
              object.babName == null ? null : fbb.writeString(object.babName!);
          final newHadithNumberOffset = fbb.writeString(object.newHadithNumber);
          final hadithTextOffset = fbb.writeString(object.hadithText);
          final bookIDOffset = fbb.writeString(object.bookID);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final annotationsOffset = object.annotations == null
              ? null
              : fbb.writeList(object.annotations!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final grade1Offset =
              object.grade1 == null ? null : fbb.writeString(object.grade1!);
          final hadithTextWithoutDiacriticsOffset =
              fbb.writeString(object.hadithTextWithoutDiacritics);
          fbb.startTable(19);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.volumeNumber);
          fbb.addInt64(2, object.bookNumber);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, babNumberOffset);
          fbb.addOffset(5, babNameOffset);
          fbb.addInt64(6, object.hadithNumber);
          fbb.addOffset(7, newHadithNumberOffset);
          fbb.addOffset(8, hadithTextOffset);
          fbb.addOffset(9, bookIDOffset);
          fbb.addInt64(10, object.ourHadithNumber);
          fbb.addInt64(11, object.matchingEnglishURN);
          fbb.addOffset(12, lastUpdatedOffset);
          fbb.addInt64(13, object.arabicURN);
          fbb.addOffset(14, annotationsOffset);
          fbb.addOffset(15, grade1Offset);
          fbb.addInt64(16, object.collection.targetId);
          fbb.addOffset(17, hadithTextWithoutDiacriticsOffset);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final arabicURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 30, 0);
          final annotationsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGetNullable(buffer, rootOffset, 32);
          final grade1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 34);
          final volumeNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final babNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final babNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final hadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final newHadithNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 18, '');
          final hadithTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final bookIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final ourHadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final matchingEnglishURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 26, 0);
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 28, '');
          final object = ARHadithModel(
              arabicURN: arabicURNParam,
              annotations: annotationsParam,
              grade1: grade1Param,
              volumeNumber: volumeNumberParam,
              bookNumber: bookNumberParam,
              bookName: bookNameParam,
              babNumber: babNumberParam,
              babName: babNameParam,
              hadithNumber: hadithNumberParam,
              newHadithNumber: newHadithNumberParam,
              hadithText: hadithTextParam,
              bookID: bookIDParam,
              ourHadithNumber: ourHadithNumberParam,
              matchingEnglishURN: matchingEnglishURNParam,
              lastUpdated: lastUpdatedParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4)
            ..hadithTextWithoutDiacritics =
                const fb.StringReader(asciiOptimization: true)
                    .vTableGet(buffer, rootOffset, 38, '');
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 36, 0);
          object.collection.attach(store);
          return object;
        }),
    BNHadithModel: obx_int.EntityDefinition<BNHadithModel>(
        model: _entities[1],
        toOneRelations: (BNHadithModel object) => [object.collection],
        toManyRelations: (BNHadithModel object) => {},
        getId: (BNHadithModel object) => object.id,
        setId: (BNHadithModel object, int id) {
          object.id = id;
        },
        objectToFB: (BNHadithModel object, fb.Builder fbb) {
          final bookNameOffset = object.bookName == null
              ? null
              : fbb.writeString(object.bookName!);
          final babNumberOffset = object.babNumber == null
              ? null
              : fbb.writeString(object.babNumber!);
          final babNameOffset =
              object.babName == null ? null : fbb.writeString(object.babName!);
          final hadithTextOffset = fbb.writeString(object.hadithText);
          final bookIDOffset = fbb.writeString(object.bookID);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final grade1Offset =
              object.grade1 == null ? null : fbb.writeString(object.grade1!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.volumeNumber);
          fbb.addInt64(2, object.bookNumber);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, babNumberOffset);
          fbb.addOffset(5, babNameOffset);
          fbb.addInt64(6, object.hadithNumber);
          fbb.addOffset(7, hadithTextOffset);
          fbb.addOffset(8, bookIDOffset);
          fbb.addInt64(9, object.ourHadithNumber);
          fbb.addInt64(10, object.matchingArabicURN);
          fbb.addOffset(11, lastUpdatedOffset);
          fbb.addInt64(12, object.banglaURN);
          fbb.addOffset(13, grade1Offset);
          fbb.addInt64(14, object.collection.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final banglaURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final grade1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final volumeNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final babNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final babNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final hadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final hadithTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final bookIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final ourHadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final matchingArabicURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final object = BNHadithModel(
              banglaURN: banglaURNParam,
              grade1: grade1Param,
              volumeNumber: volumeNumberParam,
              bookNumber: bookNumberParam,
              bookName: bookNameParam,
              babNumber: babNumberParam,
              babName: babNameParam,
              hadithNumber: hadithNumberParam,
              hadithText: hadithTextParam,
              bookID: bookIDParam,
              ourHadithNumber: ourHadithNumberParam,
              matchingArabicURN: matchingArabicURNParam,
              lastUpdated: lastUpdatedParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.collection.attach(store);
          return object;
        }),
    BookObjModel: obx_int.EntityDefinition<BookObjModel>(
        model: _entities[2],
        toOneRelations: (BookObjModel object) => [object.collection],
        toManyRelations: (BookObjModel object) => {},
        getId: (BookObjModel object) => object.id,
        setId: (BookObjModel object, int id) {
          object.id = id;
        },
        objectToFB: (BookObjModel object, fb.Builder fbb) {
          final bookNameOffset = fbb.writeString(object.bookName);
          final bookNumberOffset = fbb.writeString(object.bookNumber);
          fbb.startTable(5);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, bookNameOffset);
          fbb.addOffset(2, bookNumberOffset);
          fbb.addInt64(3, object.collection.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final bookNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final object = BookObjModel(
              bookName: bookNameParam, bookNumber: bookNumberParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.collection.attach(store);
          return object;
        }),
    Collection: obx_int.EntityDefinition<Collection>(
        model: _entities[3],
        toOneRelations: (Collection object) => [],
        toManyRelations: (Collection object) => {
              obx_int.RelInfo<Collection>.toMany(1, object.id!):
                  object.collectionLangs,
              obx_int.RelInfo<Collection>.toMany(2, object.id!):
                  object.booksNames,
              obx_int.RelInfo<ARHadithModel>.toOneBacklink(17, object.id!,
                      (ARHadithModel srcObject) => srcObject.collection):
                  object.arabicHadiths,
              obx_int.RelInfo<ENHadithModel>.toOneBacklink(15, object.id!,
                      (ENHadithModel srcObject) => srcObject.collection):
                  object.englishHadiths,
              obx_int.RelInfo<URHadithModel>.toOneBacklink(15, object.id!,
                      (URHadithModel srcObject) => srcObject.collection):
                  object.urduHadiths
            },
        getId: (Collection object) => object.id,
        setId: (Collection object, int id) {
          object.id = id;
        },
        objectToFB: (Collection object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final bookNameOffset = fbb.writeString(object.bookName);
          final arAndEnNameOffset = fbb.writeString(object.arAndEnName);
          final translationsOffset = fbb.writeList(
              object.translations.map(fbb.writeString).toList(growable: false));
          fbb.startTable(11);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, bookNameOffset);
          fbb.addOffset(3, arAndEnNameOffset);
          fbb.addBool(4, object.hasBooks);
          fbb.addBool(5, object.hasChapters);
          fbb.addOffset(6, translationsOffset);
          fbb.addInt64(7, object.totalBooksCount);
          fbb.addInt64(8, object.totalHadith);
          fbb.addInt64(9, object.totalAvailableHadith);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final arAndEnNameParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final hasBooksParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final hasChaptersParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          final translationsParam = const fb.ListReader<String>(
                  fb.StringReader(asciiOptimization: true),
                  lazy: false)
              .vTableGet(buffer, rootOffset, 16, []);
          final totalBooksCountParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          final collectionLangsParam = obx.ToMany<CollectionLang>();
          final totalHadithParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          final totalAvailableHadithParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final booksNamesParam = obx.ToMany<BookObjModel>();
          final object = Collection(
              name: nameParam,
              bookName: bookNameParam,
              arAndEnName: arAndEnNameParam,
              hasBooks: hasBooksParam,
              hasChapters: hasChaptersParam,
              translations: translationsParam,
              totalBooksCount: totalBooksCountParam,
              collectionLangs: collectionLangsParam,
              totalHadith: totalHadithParam,
              totalAvailableHadith: totalAvailableHadithParam,
              booksNames: booksNamesParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          obx_int.InternalToManyAccess.setRelInfo<Collection>(
              object.collectionLangs,
              store,
              obx_int.RelInfo<Collection>.toMany(1, object.id!));
          obx_int.InternalToManyAccess.setRelInfo<Collection>(object.booksNames,
              store, obx_int.RelInfo<Collection>.toMany(2, object.id!));
          obx_int.InternalToManyAccess.setRelInfo<Collection>(
              object.arabicHadiths,
              store,
              obx_int.RelInfo<ARHadithModel>.toOneBacklink(17, object.id!,
                  (ARHadithModel srcObject) => srcObject.collection));
          obx_int.InternalToManyAccess.setRelInfo<Collection>(
              object.englishHadiths,
              store,
              obx_int.RelInfo<ENHadithModel>.toOneBacklink(15, object.id!,
                  (ENHadithModel srcObject) => srcObject.collection));
          obx_int.InternalToManyAccess.setRelInfo<Collection>(
              object.urduHadiths,
              store,
              obx_int.RelInfo<URHadithModel>.toOneBacklink(15, object.id!,
                  (URHadithModel srcObject) => srcObject.collection));
          return object;
        }),
    CollectionLang: obx_int.EntityDefinition<CollectionLang>(
        model: _entities[4],
        toOneRelations: (CollectionLang object) => [object.collection],
        toManyRelations: (CollectionLang object) => {},
        getId: (CollectionLang object) => object.id,
        setId: (CollectionLang object, int id) {
          object.id = id;
        },
        objectToFB: (CollectionLang object, fb.Builder fbb) {
          final langOffset = fbb.writeString(object.lang);
          final titleOffset = fbb.writeString(object.title);
          final shortIntroOffset = fbb.writeString(object.shortIntro);
          fbb.startTable(6);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addOffset(1, langOffset);
          fbb.addOffset(2, titleOffset);
          fbb.addOffset(3, shortIntroOffset);
          fbb.addInt64(4, object.collection.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final langParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final shortIntroParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = CollectionLang(
              lang: langParam, title: titleParam, shortIntro: shortIntroParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.collection.attach(store);
          return object;
        }),
    ENHadithModel: obx_int.EntityDefinition<ENHadithModel>(
        model: _entities[5],
        toOneRelations: (ENHadithModel object) => [object.collection],
        toManyRelations: (ENHadithModel object) => {},
        getId: (ENHadithModel object) => object.id,
        setId: (ENHadithModel object, int id) {
          object.id = id;
        },
        objectToFB: (ENHadithModel object, fb.Builder fbb) {
          final bookNameOffset = object.bookName == null
              ? null
              : fbb.writeString(object.bookName!);
          final babNumberOffset = object.babNumber == null
              ? null
              : fbb.writeString(object.babNumber!);
          final babNameOffset =
              object.babName == null ? null : fbb.writeString(object.babName!);
          final hadithTextOffset = fbb.writeString(object.hadithText);
          final bookIDOffset = fbb.writeString(object.bookID);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final grade1Offset =
              object.grade1 == null ? null : fbb.writeString(object.grade1!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.volumeNumber);
          fbb.addInt64(2, object.bookNumber);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, babNumberOffset);
          fbb.addOffset(5, babNameOffset);
          fbb.addInt64(6, object.hadithNumber);
          fbb.addOffset(7, hadithTextOffset);
          fbb.addOffset(8, bookIDOffset);
          fbb.addInt64(9, object.ourHadithNumber);
          fbb.addInt64(10, object.matchingArabicURN);
          fbb.addOffset(11, lastUpdatedOffset);
          fbb.addInt64(12, object.englishURN);
          fbb.addOffset(13, grade1Offset);
          fbb.addInt64(14, object.collection.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final englishURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final grade1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final volumeNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final babNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final babNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final hadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final hadithTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final bookIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final ourHadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final matchingArabicURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final object = ENHadithModel(
              englishURN: englishURNParam,
              grade1: grade1Param,
              volumeNumber: volumeNumberParam,
              bookNumber: bookNumberParam,
              bookName: bookNameParam,
              babNumber: babNumberParam,
              babName: babNameParam,
              hadithNumber: hadithNumberParam,
              hadithText: hadithTextParam,
              bookID: bookIDParam,
              ourHadithNumber: ourHadithNumberParam,
              matchingArabicURN: matchingArabicURNParam,
              lastUpdated: lastUpdatedParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.collection.attach(store);
          return object;
        }),
    URHadithModel: obx_int.EntityDefinition<URHadithModel>(
        model: _entities[6],
        toOneRelations: (URHadithModel object) => [object.collection],
        toManyRelations: (URHadithModel object) => {},
        getId: (URHadithModel object) => object.id,
        setId: (URHadithModel object, int id) {
          object.id = id;
        },
        objectToFB: (URHadithModel object, fb.Builder fbb) {
          final bookNameOffset = object.bookName == null
              ? null
              : fbb.writeString(object.bookName!);
          final babNumberOffset = object.babNumber == null
              ? null
              : fbb.writeString(object.babNumber!);
          final babNameOffset =
              object.babName == null ? null : fbb.writeString(object.babName!);
          final hadithTextOffset = fbb.writeString(object.hadithText);
          final bookIDOffset = fbb.writeString(object.bookID);
          final lastUpdatedOffset = fbb.writeString(object.lastUpdated);
          final grade1Offset =
              object.grade1 == null ? null : fbb.writeString(object.grade1!);
          fbb.startTable(16);
          fbb.addInt64(0, object.id ?? 0);
          fbb.addInt64(1, object.volumeNumber);
          fbb.addInt64(2, object.bookNumber);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, babNumberOffset);
          fbb.addOffset(5, babNameOffset);
          fbb.addInt64(6, object.hadithNumber);
          fbb.addOffset(7, hadithTextOffset);
          fbb.addOffset(8, bookIDOffset);
          fbb.addInt64(9, object.ourHadithNumber);
          fbb.addInt64(10, object.matchingArabicURN);
          fbb.addOffset(11, lastUpdatedOffset);
          fbb.addInt64(12, object.urduURN);
          fbb.addOffset(13, grade1Offset);
          fbb.addInt64(14, object.collection.targetId);
          fbb.finish(fbb.endTable());
          return object.id ?? 0;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final urduURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 28, 0);
          final grade1Param = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 30);
          final volumeNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final bookNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 10);
          final babNumberParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 12);
          final babNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 14);
          final hadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final hadithTextParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 18, '');
          final bookIDParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 20, '');
          final ourHadithNumberParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 22, 0);
          final matchingArabicURNParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0);
          final lastUpdatedParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 26, '');
          final object = URHadithModel(
              urduURN: urduURNParam,
              grade1: grade1Param,
              volumeNumber: volumeNumberParam,
              bookNumber: bookNumberParam,
              bookName: bookNameParam,
              babNumber: babNumberParam,
              babName: babNameParam,
              hadithNumber: hadithNumberParam,
              hadithText: hadithTextParam,
              bookID: bookIDParam,
              ourHadithNumber: ourHadithNumberParam,
              matchingArabicURN: matchingArabicURNParam,
              lastUpdated: lastUpdatedParam)
            ..id =
                const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 4);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 32, 0);
          object.collection.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ARHadithModel] entity fields to define ObjectBox queries.
class ARHadithModel_ {
  /// see [ARHadithModel.id]
  static final id =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[0]);

  /// see [ARHadithModel.volumeNumber]
  static final volumeNumber =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[1]);

  /// see [ARHadithModel.bookNumber]
  static final bookNumber =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[2]);

  /// see [ARHadithModel.bookName]
  static final bookName =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[3]);

  /// see [ARHadithModel.babNumber]
  static final babNumber =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[4]);

  /// see [ARHadithModel.babName]
  static final babName =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[5]);

  /// see [ARHadithModel.hadithNumber]
  static final hadithNumber =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[6]);

  /// see [ARHadithModel.newHadithNumber]
  static final newHadithNumber =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[7]);

  /// see [ARHadithModel.hadithText]
  static final hadithText =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[8]);

  /// see [ARHadithModel.bookID]
  static final bookID =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[9]);

  /// see [ARHadithModel.ourHadithNumber]
  static final ourHadithNumber =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[10]);

  /// see [ARHadithModel.matchingEnglishURN]
  static final matchingEnglishURN =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[11]);

  /// see [ARHadithModel.lastUpdated]
  static final lastUpdated =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[12]);

  /// see [ARHadithModel.arabicURN]
  static final arabicURN =
      obx.QueryIntegerProperty<ARHadithModel>(_entities[0].properties[13]);

  /// see [ARHadithModel.annotations]
  static final annotations =
      obx.QueryStringVectorProperty<ARHadithModel>(_entities[0].properties[14]);

  /// see [ARHadithModel.grade1]
  static final grade1 =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[15]);

  /// see [ARHadithModel.collection]
  static final collection = obx.QueryRelationToOne<ARHadithModel, Collection>(
      _entities[0].properties[16]);

  /// see [ARHadithModel.hadithTextWithoutDiacritics]
  static final hadithTextWithoutDiacritics =
      obx.QueryStringProperty<ARHadithModel>(_entities[0].properties[17]);
}

/// [BNHadithModel] entity fields to define ObjectBox queries.
class BNHadithModel_ {
  /// see [BNHadithModel.id]
  static final id =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[0]);

  /// see [BNHadithModel.volumeNumber]
  static final volumeNumber =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[1]);

  /// see [BNHadithModel.bookNumber]
  static final bookNumber =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[2]);

  /// see [BNHadithModel.bookName]
  static final bookName =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[3]);

  /// see [BNHadithModel.babNumber]
  static final babNumber =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[4]);

  /// see [BNHadithModel.babName]
  static final babName =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[5]);

  /// see [BNHadithModel.hadithNumber]
  static final hadithNumber =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[6]);

  /// see [BNHadithModel.hadithText]
  static final hadithText =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[7]);

  /// see [BNHadithModel.bookID]
  static final bookID =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[8]);

  /// see [BNHadithModel.ourHadithNumber]
  static final ourHadithNumber =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[9]);

  /// see [BNHadithModel.matchingArabicURN]
  static final matchingArabicURN =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[10]);

  /// see [BNHadithModel.lastUpdated]
  static final lastUpdated =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[11]);

  /// see [BNHadithModel.banglaURN]
  static final banglaURN =
      obx.QueryIntegerProperty<BNHadithModel>(_entities[1].properties[12]);

  /// see [BNHadithModel.grade1]
  static final grade1 =
      obx.QueryStringProperty<BNHadithModel>(_entities[1].properties[13]);

  /// see [BNHadithModel.collection]
  static final collection = obx.QueryRelationToOne<BNHadithModel, Collection>(
      _entities[1].properties[14]);
}

/// [BookObjModel] entity fields to define ObjectBox queries.
class BookObjModel_ {
  /// see [BookObjModel.id]
  static final id =
      obx.QueryIntegerProperty<BookObjModel>(_entities[2].properties[0]);

  /// see [BookObjModel.bookName]
  static final bookName =
      obx.QueryStringProperty<BookObjModel>(_entities[2].properties[1]);

  /// see [BookObjModel.bookNumber]
  static final bookNumber =
      obx.QueryStringProperty<BookObjModel>(_entities[2].properties[2]);

  /// see [BookObjModel.collection]
  static final collection = obx.QueryRelationToOne<BookObjModel, Collection>(
      _entities[2].properties[3]);
}

/// [Collection] entity fields to define ObjectBox queries.
class Collection_ {
  /// see [Collection.id]
  static final id =
      obx.QueryIntegerProperty<Collection>(_entities[3].properties[0]);

  /// see [Collection.name]
  static final name =
      obx.QueryStringProperty<Collection>(_entities[3].properties[1]);

  /// see [Collection.bookName]
  static final bookName =
      obx.QueryStringProperty<Collection>(_entities[3].properties[2]);

  /// see [Collection.arAndEnName]
  static final arAndEnName =
      obx.QueryStringProperty<Collection>(_entities[3].properties[3]);

  /// see [Collection.hasBooks]
  static final hasBooks =
      obx.QueryBooleanProperty<Collection>(_entities[3].properties[4]);

  /// see [Collection.hasChapters]
  static final hasChapters =
      obx.QueryBooleanProperty<Collection>(_entities[3].properties[5]);

  /// see [Collection.translations]
  static final translations =
      obx.QueryStringVectorProperty<Collection>(_entities[3].properties[6]);

  /// see [Collection.totalBooksCount]
  static final totalBooksCount =
      obx.QueryIntegerProperty<Collection>(_entities[3].properties[7]);

  /// see [Collection.totalHadith]
  static final totalHadith =
      obx.QueryIntegerProperty<Collection>(_entities[3].properties[8]);

  /// see [Collection.totalAvailableHadith]
  static final totalAvailableHadith =
      obx.QueryIntegerProperty<Collection>(_entities[3].properties[9]);

  /// see [Collection.collectionLangs]
  static final collectionLangs =
      obx.QueryRelationToMany<Collection, CollectionLang>(
          _entities[3].relations[0]);

  /// see [Collection.booksNames]
  static final booksNames = obx.QueryRelationToMany<Collection, BookObjModel>(
      _entities[3].relations[1]);

  /// see [Collection.arabicHadiths]
  static final arabicHadiths =
      obx.QueryBacklinkToMany<ARHadithModel, Collection>(
          ARHadithModel_.collection);

  /// see [Collection.englishHadiths]
  static final englishHadiths =
      obx.QueryBacklinkToMany<ENHadithModel, Collection>(
          ENHadithModel_.collection);

  /// see [Collection.urduHadiths]
  static final urduHadiths = obx.QueryBacklinkToMany<URHadithModel, Collection>(
      URHadithModel_.collection);
}

/// [CollectionLang] entity fields to define ObjectBox queries.
class CollectionLang_ {
  /// see [CollectionLang.id]
  static final id =
      obx.QueryIntegerProperty<CollectionLang>(_entities[4].properties[0]);

  /// see [CollectionLang.lang]
  static final lang =
      obx.QueryStringProperty<CollectionLang>(_entities[4].properties[1]);

  /// see [CollectionLang.title]
  static final title =
      obx.QueryStringProperty<CollectionLang>(_entities[4].properties[2]);

  /// see [CollectionLang.shortIntro]
  static final shortIntro =
      obx.QueryStringProperty<CollectionLang>(_entities[4].properties[3]);

  /// see [CollectionLang.collection]
  static final collection = obx.QueryRelationToOne<CollectionLang, Collection>(
      _entities[4].properties[4]);
}

/// [ENHadithModel] entity fields to define ObjectBox queries.
class ENHadithModel_ {
  /// see [ENHadithModel.id]
  static final id =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[0]);

  /// see [ENHadithModel.volumeNumber]
  static final volumeNumber =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[1]);

  /// see [ENHadithModel.bookNumber]
  static final bookNumber =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[2]);

  /// see [ENHadithModel.bookName]
  static final bookName =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[3]);

  /// see [ENHadithModel.babNumber]
  static final babNumber =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[4]);

  /// see [ENHadithModel.babName]
  static final babName =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[5]);

  /// see [ENHadithModel.hadithNumber]
  static final hadithNumber =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[6]);

  /// see [ENHadithModel.hadithText]
  static final hadithText =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[7]);

  /// see [ENHadithModel.bookID]
  static final bookID =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[8]);

  /// see [ENHadithModel.ourHadithNumber]
  static final ourHadithNumber =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[9]);

  /// see [ENHadithModel.matchingArabicURN]
  static final matchingArabicURN =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[10]);

  /// see [ENHadithModel.lastUpdated]
  static final lastUpdated =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[11]);

  /// see [ENHadithModel.englishURN]
  static final englishURN =
      obx.QueryIntegerProperty<ENHadithModel>(_entities[5].properties[12]);

  /// see [ENHadithModel.grade1]
  static final grade1 =
      obx.QueryStringProperty<ENHadithModel>(_entities[5].properties[13]);

  /// see [ENHadithModel.collection]
  static final collection = obx.QueryRelationToOne<ENHadithModel, Collection>(
      _entities[5].properties[14]);
}

/// [URHadithModel] entity fields to define ObjectBox queries.
class URHadithModel_ {
  /// see [URHadithModel.id]
  static final id =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[0]);

  /// see [URHadithModel.volumeNumber]
  static final volumeNumber =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[1]);

  /// see [URHadithModel.bookNumber]
  static final bookNumber =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[2]);

  /// see [URHadithModel.bookName]
  static final bookName =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[3]);

  /// see [URHadithModel.babNumber]
  static final babNumber =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[4]);

  /// see [URHadithModel.babName]
  static final babName =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[5]);

  /// see [URHadithModel.hadithNumber]
  static final hadithNumber =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[6]);

  /// see [URHadithModel.hadithText]
  static final hadithText =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[7]);

  /// see [URHadithModel.bookID]
  static final bookID =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[8]);

  /// see [URHadithModel.ourHadithNumber]
  static final ourHadithNumber =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[9]);

  /// see [URHadithModel.matchingArabicURN]
  static final matchingArabicURN =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[10]);

  /// see [URHadithModel.lastUpdated]
  static final lastUpdated =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[11]);

  /// see [URHadithModel.urduURN]
  static final urduURN =
      obx.QueryIntegerProperty<URHadithModel>(_entities[6].properties[12]);

  /// see [URHadithModel.grade1]
  static final grade1 =
      obx.QueryStringProperty<URHadithModel>(_entities[6].properties[13]);

  /// see [URHadithModel.collection]
  static final collection = obx.QueryRelationToOne<URHadithModel, Collection>(
      _entities[6].properties[14]);
}
