const Map<String, String> textsEn = {
  "home": "Home",
  "all-departments": "All departments",
  "count-hadiths": "Number of Hadiths",
  "all-res": "All results",
  "source": "The source",
  "hadith-degree": "Hadith degree",
  "hadith-text": "Text of the Hadith",
  "hadith-explanation": "Explanation of the hadith",
  "hadith-vocabulary": "Selected vocabulary from the hadith",
  "hadith-vocabulary-not": "There are no selected vocabulary for this hadith.",
  "hadith-benefits": "Benefits of Hadith",
  "hadith-references": "The References",
  "hadith-references-not": "There are no references available for this hadith",
  "aboutUs": "About Us",
  "title-slider1": "Authentic Prophetic Hadiths",
  "title-slider2": "Checking the authenticity of the Hadith",
  "title-slider3": "Reviewing the explanation of the Hadith briefly",
  "contact-us": "Contact Us",
  "Edit-account": "Edit Account",
  "book-marks": "Bookmarks",
  "selectLanguage": "Select Language",
  "account-settings": "Account Settings",
  "personal-information": "Personal Information",
  "logout_sure": "Are you sure you want to log out?",
  "notifications": "Notifications",
  "comment-valid1": "Please enter a comment",
  "comment-valid2": "The comment must contain at least 2 characters",
  "personal-image": "Profile Picture",
  "profile": "Profile",
  "policy": "Privacy Policy",
  "frequently": "Frequently Asked Questions",
  "share": "Share App",
  "follow": "Follow us on",
  "change": "Change",
  "first-name": "First Name",
  "last-name": "Last Name",
  "phone-number": "Phone Number",
  "next": "Next",
  "confirm": "Confirm",
  "onBoard-enter": "Enter",
  "onBoard-next": "Next",
  "onBoard-text1": "A comprehensive and diverse set of tests",
  "onBoard-text2":
      "Helping students achieve their academic and professional goals",
  "onBoard-text3": "Achieve the best results in tests",
  "onBoard-des1":
      "The app offers a comprehensive and diverse set of academic, linguistic, and professional tests.",
  "onBoard-des2":
      "Helping students achieve their academic and professional goals by providing them with the necessary skills and confidence through test simulations and feedback.",
  "onBoard-des3":
      "The app offers a range of resources such as study materials, practice questions, and tips to achieve the best test results.",
  "notify-1": "Suggest suitable tests for you and send them via email",
  "notify-2": "Send notifications of new updates",
  "exams-search": "Search for a recent...",
  "notFound":
      "We couldn't find any matches for your search. Try using different terms.",
  "notSearchFound": "No search results found",
  "vision": "Vision and Mission",
  "logout": "Log Out",
  "goCatePage": "Navigate to All Categories",
  "country": "Country",
  "selectCountry": "Select Country",
  "activate": "Activate",
  "cart": "Add to Cart",
  "cart2": "Cart",
  "delete": "Delete",
  "welcome": "Welcome !",
  "reliability": "Reliability of sources",
  "reliabilityDes":
      "All hadiths are classified and reviewed from reliable sources.",
  "purposefulLearning": "purposeful learning",
  "purposefulDes":
      "An integrated educational methodology to understand the Prophet’s Sunnah",
  "EaseOfUse": "Ease of use",
  "EaseOfUseDes": "Intuitive and smooth interface for browsing and searching",
  "TrackLearning": "Track learning",
  "TrackLearningDes": "Advanced tools to track your achievements and progress.",
  "amount": "Amount",
  "exploreNow": "Explore now",
  "discounts": "Discounts",
  "promocode": "Promo Code",
  "platform-des":
      "A comprehensive platform for studying the hadiths and the biography of the Prophet",
  "total": "Total",
  "pay": "Pay",
  "tryTotal": "Number of Attempts",
  "camera": "Camera",
  "gallery": "Gallery",
  "selectImg": "Select Image",
  "dollar": "Dollar",
  "delete-cart": "Delete all items in the cart?",
  "free": "Free",
  "allrights-copy": "All rights reserved 2023",
  "important-links": "Important Links",
  "exam-created": "Created by:",
  "rating-opinion": "Ratings and Reviews",
  "overview": "Overview",
  "add-comment": "Add your comment",
  "cancel": "Cancel",
  "write-comment": "Write your comment here",
  "type": "Type",
  "date": "Date",
  "time": "Time",
  "ratio": "Ratio",
  "status": "Status",
  "reports": "Reports",
  "number-reviews": "Number of Reviews",
  "level": "Level",
  "minute": "Minute",
  "medium": "Medium",
  "view-reports": "View",
  "buy-free": "Confirm Purchase / Free",
  "buy-now": "Confirm Purchase",
  "instead": "Instead of",
  "training-first": "Train First",
  "login": "Login",
  "question": "Question",
  "from": "From",
  "skip": "Skip",
  "previous": "Previous",
  "summary": "Summary",
  "time-taken": "Time Taken",
  "second": "Seconds",
  "very-easy": "Very Easy",
  "navigate": "Navigate",
  "purchased": "Purchased",
  "post-blog": "Posted on:",
  "read-more": "Read More",
  "delete-comment": "Delete Comment",
  "free-register": "Register for Free",
  "view-all": "View All",
  "placement": "Placement",
  "why-student": "Why Students Love",
  "student-name": "Ali Abdul Hadi - High School Student",
  "student-word":
      "“I was able to prepare very well before the term exam. I solved more than 20 exercises in all subjects, and the exam did not go beyond them. Thank God, I achieved full marks in most subjects. Thank you, Yaqees.”",
  "FAQs": "Frequently Asked Questions",
  "What-platform": "What is the Yaqees platform?",
  "yaqees-beneift":
      "What will I benefit from subscribing to the Yaqees platform?",
  "free-subscribe": "Is the subscription free?",
  "yaqees-source": "What is the source of Yaqees tests?",
  "level-analysis": "How does Yaqees analyze the learner's level?",
  "print": "Print",
  "appTitle": "Model",
  "lang": "Language",
  "theme": "Theme",
  "light": "Light Mode",
  "dark": "Dark Mode",
  "system": "System Default",
  "en": "En",
  "ar": "Ar",
  "click": "Click",
  "enterEmail": "Enter Email",
  "enterPassword": "Enter Password",
  "enterConfirmPassword": "Enter Confirm Password",
  "username": "Username",
  "enterUsername": "Enter Username",
  "login_now": "Login",
  "no_connection": "It seems you have no internet connection",
  "try_later": "Something went wrong, try again later",
  "location_denaid": "Location access denied!",
  "location_denaid_permanently":
      "Location permissions are permanently denied and we cannot request permissions.",
  "location_disabled": "Location services are disabled.",
  "try_again": "Try Again",
  "full_name": "Full Name",
  "phone_number": "Phone Number",
  "email": "Email",
  "password": "Password",
  "register_success": "Congratulations, registration was successful.",
  "login_success": "Congratulations, Login was successful.",
  "forget_password": "Forgot Password?",
  "app_welcom": "Welcome to the Mishkat Al-Ahadith app",
  "app_name": "Mishkat Al-Ahadith",
  "Login_now": "Log in to continue your learning journey",
  "register_now":
      "Register now and start your journey with Mishkat Al-Ahadith.",
  "regNow": "Register Now",
  "dont_have_acc": "Don't have an account?",
  "e-mailVerification": "Email Verification",
  "email_Verification": "Account Activation Code",
  "sign_up": "Join Us",
  "create_account": "Create Account",
  "already_have_an_account": "Already have an account?",
  "register": "Create Account",
  "phone": "Mobile Number",
  "signin": "Sign In",
  "forgot": "Forgot Password",
  "lablePhone": "Email or Phone Number",
  "or": "or",
  "google": "Sign in with Google",
  "enterTax": "Enter price including 15% tax",
  "loginEmail": "Sign in with Email",
  "loginPhone": "Sign in with Phone",
  "apple": "Sign in with Apple",
  "recover": "Recover Password",
  "recoverSuccesse": "Recovery Success",
  "continue": "Confirm",
  "recavry_password": "We will send you the code to your email",
  "recoverlable": "Email Address",
  "recovertext": "Enter the registered email address to recover the password",
  "recoverPassword": "Create New Password",
  "recovertextSuccesse":
      "An email has been sent with a link to enter the new password",
  "newPassword": "New Password",
  "newPasswordText":
      "The new password must be different from the old one to make the account more secure",
  "newPasswordLable": "Password",
  "newPasswordConfirmLable": "Confirm Password",
  "signup": "New Account",
  "signupName": "Full Name",
  "signupPhone": "Phone Number",
  "signupCity": "City (Optional)",
  "signupEmail": "Email Address",
  "signupPassword": "Password",
  "signupConfirm": "Confirm Password",
  "signupRegister": "Register Now",
  "registerFree": "Register for Free",
  "signupAgree": "I agree with the terms and policy",
  "verification": "Verification Code",
  "veritificationtext": "Enter the OTP authentication code below",
  "s": "s",
  "resend": "Resend Code",
  "search": "Search for a game or platform...",
  "platforms": "Platforms",
  "categories": "Categories",
  "ads": "Ads",
  "filter": "Filter",
  "newPost": "Add your ad now",
  "seeAll": "See All",
  "playstation": "PlayStation",
  "drawerHome": "Home",
  "drawerProfile": "Profile",
  "drawerDashboard": "Dashboard",
  "drawerSettings": "Settings",
  "drawerExams": "Exams",
  "drawerBlog": "Blog",
  "more": "More",
  "drawerOrders": "My Orders",
  "drawerFavorites": "Favorites",
  "drawerCard": "Shopping Cart",
  "drawerMessages": "Messages",
  "drawerAds": "My Ads",
  "drawerContact": "Contact Us",
  "drawerHelp": "Help",
  "drawerTerms&Condition": "Terms and Conditions",
  "drawerRegisterTrader": "Register as Trader",
  "drawerLogOut": "Log Out",
  "logOut": "Log Out",
  "lg": "EN",
  "personal_Information": "Personal Information",
  "edit": "Edit",
  "privacy_setting": "Privacy Settings",
  "change_password": "Change Password",
  "avatars": "Avatars",
  "IBAN": "IBAN",
  "favorite": "Favorite",
  "chat": "Ask",
  "aboutThisGame": "About This Product",
  "price": "Price",
  "published": "Published",
  "buy": "Buy",
  "games": "Games",
  "all": "All",
  "x-box": "Xbox",
  "pc": "PC",
  "chatTextInput": "Ask for something here.",
  "newAd": "New Ad",
  "itemName": "Item Name",
  "coverPhoto": "Upload Cover Photo",
  "currentLocation": "Current Location",
  "quantity": "QTY",
  "weight": "Weight",
  "phoneNumber": "Mobile Number",
  "description": "Details",
  "uploadPhoto": "Upload Photo",
  "only8Photos": "You can only add up to 6 photos",
  "sendHand": "Hand Delivery",
  "sendComant": "Send with Shipping Company",
  "iAgreeWith": "I agree with",
  "termsAndConditions": "Terms and Conditions",
  "save": "Save",
  "post": "Post",
  "allExams": "All Exams",
  "choose": "Choose",
  "fullName": "Full Name",
  "bankName": "Bank Name",
  "changeAvatar": "Change your avatar?",
  "yes": "Yes",
  "no": "No",
  "wallet": "My Wallet",
  "yourProfit": "Available Balance",
  "receiveTheAmount": "You will receive the amount upon selling the order",
  "numberOfOrders": "Number of Orders",
  "numberReceived": "Received",
  "inProgress": "In Progress",
  "completed": "Completed",
  "canceled": "Canceled",
  "orderId": "Order ID",
  "confirmReceiving": "Confirm Receipt",
  "chatWithTheBuyer": "Chat with the Seller",
  "details": "Details",
  "rateOrder": "Rate Order",
  "done": "Done",
  "ok": "OK",
  "confirmNewPass": "Confirm",
  "VAT": "VAT:",
  "paymentMethod": "Payment Method:",
  "deliveryMethod": "Delivery Method:",
  "orderDiscount": "Discount Rate:",
  "deliveryDate": "Delivery Date:",
  "personalPromoCode": "Personal Promo Code",
  "tybeSomethingHere": "Type something here",
  "ordersDetails": "Order Details",
  "gamersStore": "About This Game",
  "productDeliveryOptions": "Product Delivery Options",
  "year": "Years",
  "yearOne": "One Year Ago",
  "yearTow": "Two Years Ago",
  "month": "Months",
  "monthOne": "One Month Ago",
  "monthTow": "Two Months Ago",
  "weeks": "Weeks",
  "weeksOne": "One Week Ago",
  "weeksTwo": "Two Weeks Ago",
  "today": "Today",
  "hours": "Hours",
  "minutes": "Minutes",
  "day": "Days",
  "SendMessage": "Send Message",
  "Send request": "Send Request",
  "customerRating": "Customer Rating",
  "paymentMethodShipping": "Payment Method",
  "orderReview": "Order Review",
  "discountCodes": "Discount Code",
  "billingSummary": "Billing Summary",
  "cardNumber": "Card Number",
  "ZipCode": "Zip Code",
  "cardSecurityCode": "Card Security Code",
  "paymentSecurity":
      "We protect your payment information using encryption to provide bank-level security.",
  "whatThis": "What is this?",
  "itemsCard": "Items in Cart",
  "validationCode": "Enter the code sent to",
  "correctCode": "Please enter the correct activation code.",
  "fillAllCode":
      "** Please complete entering the activation code in the fields.",
  "EnterCouponCode": "Enter your coupon code",
  "subtotal": "Subtotal",
  "discount": "Discount",
  "shipping": "Shipping",
  "tax": "Tax",
  "pleaseCheckL": "our",
  "securityCheckout": "Secure Checkout",
  "shippingInformation": "Shipping Information",
  "receivingMethod": "Receiving Method",
  "deliveryMethodShipping": "Delivery Method",
  "region": "Region",
  "city": "City",
  "neighborhood": "Neighborhood",
  "street": "Street",
  "buildingNumber": "Building Number",
  "maximumQuantity": "Sorry, you have reached the maximum quantity",
  "disc": "Discount",
  "name": "Name",
  "confirmAddress": "Confirm Address",
  "addNewAddress": "Add New Address",
  "Home": "Primary Address",
  "itemInformation": "Product Information",
  "length": "Length",
  "width": "Width",
  "height": "Height",
  "otherDetails": "Other Details",
  "qty": "Quantity",
  "submitProfitRequest": "Submit Profit Transfer Request",
  "profit": "Transfer",
  "confirmation": "Confirmation",
  "errors": "Error",
  "You don't have any profits already to transfer":
      "You don't have any profits to transfer",
  "doSubmitProfitRequest": "Do you want to submit a profit request?",
  "submitRequest": "Submit Request",
  "shippingInformtion": "Shipping Information",
  "district": "District",
  "postalCode": "Postal Code",
  "emailAddress": "Email Address",
  "getInTouch": "I'd love to hear from you, get in touch with us 👋🏻",
  "send": "Send",
  "myAds": "My Ads",
  "active": "Active",
  "inactive": "Inactive",
  "sold": "Sold",
  "myAdscanceled": "Canceled",
  "proofTransaction": "Receipt",
  "validName": "Enter a valid name",
  "validMessage": "Enter a valid message, more than 8 characters",
  "validEmail": "Enter a valid email",
  "two-syllableName": "Enter a valid two-syllable name",
  "couldNotSend": "Sorry, the message was not sent",
  "thankContacting": "Thank you for contacting us",
  "privacy&Responsibilities": "Privacy Policy and Responsibilities",
  "aboutUsContent":
      "We are the (GG) website owned by (Good Game) for electronic marketing, a Saudi institution with full Saudi management. We specialize in marketing and promoting goods, products, and information about others, whether an individual, institution, or company. The institution specializes in everything related to electronic games, whether devices, products, information, or spare parts. The (GG) website allows the user, whether an individual, institution, or company, to display their products by creating an ad on the site. It also allows the user, whether an individual, institution, or company, to purchase any product advertised by users, provided it does not conflict with the site's usage rules and policies.",
  "installmentService": "Installment Service from",
  "expiryDate": "Expiry Date",
  "validPassword": "Password must be at least 6 characters.",
  "validConfirmPassword": "Confirm password does not match the password",
  "validPhone": "Enter a valid phone number",
  "\$": "SAR",
  "purchaseOrder": "Purchase Order",
  "buyerInformation": "Buyer Information",
  "address": "Address",
  "paymentStatus": "Payment Status",
  "paid": "Paid",
  "sentConfirmation": "Item Delivery Confirmation",
  "selectLocation": "Select Pickup Location",
  "myAdsShipping": "Shipping",
  "updateAdHite": "Do you want to update the ad?",
  "deleteAd": "Delete Ad?",
  "deleteAdHite":
      "Do you want to permanently delete the ad or temporarily hide it?",
  "saveAd": "Save Ad?",
  "saveAdHite": "Do you want to save the ad?",
  "hide": "Hide",
  "checkNetwork": "Please check your internet connection",
  "failedLoad": "Something went wrong",
  "tryِAgain": "Try Again",
  "newMessage": "New Message",
  "image": "Image",
  "location": "Location",
  "update": "Update",
  "select": "Select",
  "addAddres": "Add Address",
  "cm": "cm",
  "kg": "kg",
  "removeCart": "Remove ad from cart",
  "removeCartHint": "Are you sure you want to remove the ad from the cart?",
  "publishOrJust": "Do you want to publish the ad or just save the edit?",
  "publish": "Publish",
  "cardholder": "Cardholder Name",
  "wrong-password": "The password is invalid for the specified email.",
  "invalid-email": "The email address is invalid.",
  "user-not-found": "No user found for the specified email.",
  "user-disabled":
      "The user corresponding to the specified email has been disabled.",
  "email-already-in-use":
      "An account already exists with the specified email address.",
  "operation-not-allowed": "Email/password accounts are not enabled.",
  "weak-password": "The password is not strong enough.",
  "account-exists-with-different-credential":
      "An error occurred, please try again",
  "invalid-verification-code":
      "The verification code for the credentials is invalid.",
  "invalid-verification-id":
      "The verification code for the credentials is invalid.",
  "invalid-credential": "An error occurred, please try again",
  "expired-action-code": "The OTP link in the email has expired.",
  "FirebaseException": "Network error! Check your internet connection.",
  "ERROR_USER_NOT_FOUND": "User not found!",
  "ERROR_TOO_MANY_REQUESTS": "Too many requests!",
  "ERROR_INVALID_EMAIL": "Invalid email!",
  "ERROR_OPERATION_NOT_ALLOWED": "Operation not allowed",
  "requires-recent-login":
      "This operation is sensitive and requires recent authentication. Log in again before retrying this request.",
  "DEFAULT": "An error occurred, please try again",
  "successConfirm": "Congratulations!",
  "lableConfirm":
      "Your order will be delivered soon\n! Thank you for choosing our app",
  "seeOrder": "View My Orders",
  "availabilityCode": "Enter Availability Code",
  "enterDiscountCode": "Enter Discount Code",
  "discountCode": "Discount Code",
  "goHomePage": "Go to Home Page",
  "AdNotAvailable": "Sorry, the ad is not available now",
  "ad": "Ad",
  "account-activation": "Account Activation",
  "quantityAvailable": "Quantity Available",
  "numberAlreadyRegistered": "Phone number already registered",
  "completeProfile": "Complete Profile",
  "settings": "Settings",
  "completeProfileContect":
      "Please add your mobile number and email to your profile first",
  "profilePersonly": "Profile",
  "tryAgane": "Try Again",
  "completeAddress": "Please complete the address information",
  "productBeenSent": "Has the product been sent?",
  "locationNotSpecified": "Location not specified",
  "downloadComplete": "Download complete",
  "unableApple": "Unable to connect to Apple account",
  "unableGoogle": "Unable to connect to Google account",
  "emailRequirement": "Email is required",
  "error": "Something went wrong, please try again",
  "unavailable": "Service is currently unavailable. Please try again later.",
  "unknown": "An unknown error occurred. Please check the server response.",
  "loginAccount": "Login",
  "recover_password": "Recover Password",
  "signInFirst": "You need to sign in first",
  "login/register":
      "Please login/register first to proceed with the transaction",
  "loginFirst": "You must login first",
  "loginEnter": "Enter",
  "enterCode": "Enter the code sent to",
  "sendVerification": "Verify",
  "remove": "Remove",
  "password_validator1": "Please enter your password.",
  "password_validator2": "Password must be at least 6 characters",
  "name_validator1": "Please enter your name.",
  "name_validator2": "Name must be at least 6 characters",
  "email_validator1": "Please enter your email.",
};
