const Map<String, String> textsAr = {
  "home": "الرئيسية",
  "all-departments": "كل الاقسام ",
  "aboutUs": "عنا",
  "count-hadiths": "عدد الاحاديث",
  "all-res": "كل النتائج",
  "source": "المصدر",
  "hadith-degree": "درجة الحديث",
  "hadith-text": "نص الحديث",
  "hadith-explanation": "شرح الحديث",
  "hadith-vocabulary": "مفردات مختارة من الحديث",
  "hadith-vocabulary-not": "لا توجد مفردات مختارة لهذا الحديث",
  "hadith-benefits": "من فوائد الحديث",
  "hadith-references": "المراجع",
  "hadith-references-not": "لا توجد مراجع متاحة لهذا الحديث",
  "contact-us": "اتصل بنا",
  "Edit-account": "تعديل الحساب",
  "selectLanguage": "اختر اللغة",
  "book-marks": "الإشارات المرجعية",
  "account-settings": "إعدادات الحساب",
  "personal-information": "المعلومات الشخصية",
  "logout_sure": "هل انت متاكد من تسجيل الخروج",
  "notifications": "الإشعارات",
  "comment-valid1": "يجب ادخال تعليق",
  "comment-valid2": "يجب أن يحتوي التعليق علي 2 حرف",
  "personal-image": "الصورة الشخصية",
  "platform-des": "منصة شاملة لدراسة الأحاديث النبوية والسيرة النبوية",
  "profile": "الملف الشخصي",
  "register_success": "تهانيا تم التسجيل بنجاح",
  "login_success": "تم تسجيل الدخول بنجاح",
  "policy": "سياسة الخصوصية",
  "frequently": "أسئلة متكررة",
  "share": "مشاركة التطبيق",
  "follow": "تابعنا علي",
  "change": "تغيير",
  "first-name": "الاسم الأول",
  "last-name": "الاسم الأخير",
  "phone-number": "رقم الهاتف",
  "next": "التالي",
  "confirm": "تأكيد",
  "onBoard-enter": " دخــــول ",
  "onBoard-next": " التـــالي ",
  "onBoard-text1": " مجموعة شاملة ومتنوعة من الاختبارات ",
  "onBoard-text2": " مساعدة الدارسين في تحقيق أهدافهم الأكاديمية والمهنية ",
  "onBoard-text3": " تحقيق أفضل النتائج في الاختبارات ",
  "onBoard-des1":
      " يقدم تطبيق يقيس مجموعة شاملة ومتنوعة من الاختبارات الأكاديمية واللغوية والمهنية. ",
  "onBoard-des2":
      "مساعدة الدارسين في تحقيق أهدافهم الأكاديمية والمهنية من خلال تزويدهم بالمهارات والثقة اللازمة من خلال محاكاة الاختبارات وتقديم التغذية الراجعة.",
  "onBoard-des3":
      "تقدم يقيس مجموعة من المصادر مثل مواد الدراسة، وأسئلة التدريب، ونصائح لتحقيق أفضل النتائج في الاختبارات.",
  "notify-1": "اقتراح اختبارات مناسبة لك وإرسالها عبر البريد الإلكتروني",
  "notify-2": "إرسال إشعارات بالتحديثات الجديدة",
  "exams-search": "بحث عن حديث ....",
  "notFound":
      "لم نتمكن من العثور على أي تطابقات لبحثك. حاول استخدام مصطلحات مختلفة.",
  "notSearchFound": "لم يتم العثور على بحث مطابق لهذة الكلمة",
  "vision": "الرؤية والرسالة",
  "logout": "تسجيل خروج",
  "country": "الدولة",
  "selectCountry": "اختر الدولة",
  "activate": "تفعيل",
  "cart": "اضف إلي عربة الشراء",
  "cart2": "عربة الشراء",
  "delete": "حذف",
  "amount": "المبلغ",
  "discounts": "خصومات",
  "promocode": "كود خصم",
  "total": "إجمالي",
  "pay": "دفع",
  "tryTotal": "عدد المحاولات",
  "camera": "الكاميرا",
  "gallery": "المعرض",
  "selectImg": "اختيار الصورة",
  "dollar": "دولار",
  "delete-cart": "حذف محتويات عربة الشراء بالكامل ؟",
  "free": " مجّانًا",
  "allrights-copy": "2023 جميع الحقوق محفوظة",
  "important-links": "روابط مهمة",
  "exam-created": "تم الإعداد بواسطة:",
  "rating-opinion": "تقييمات وآراء",
  "overview": "نظرة عامة",
  "add-comment": "أضف تعليقك",
  "cancel": "إلغاء",
  "write-comment": "اكتب تعليقك هنا",
  "type": "النوع",
  "date": "التاريخ",
  "time": "الوقت",
  "ratio": "النسبة",
  "status": "الحالة",
  "reports": "التقارير",
  "number-reviews": "عدد التقييمات",
  "level": "المستوى",
  "minute": "دقيقة",
  "medium": "متوسط",
  "view-reports": "عرض",
  "buy-free": "تأكيد الشراء / مجّانًا",
  "buy-now": "تأكيد الشراء",
  "instead": "بدلا من",
  "training-first": "تدرب أولاً",
  "login": "تسجيل دخول",
  "question": "السؤال",
  "from": "من",
  "skip": "تخطي",
  "previous": "السابق",
  "summary": "ملخص",
  "time-taken": "الوقت المستغرق",
  "second": "ثوانٍ",
  "very-easy": "سهل جدًا",
  "navigate": "إنتقال",
  "purchased": "تم شراءه",
  "post-blog": "تم النشر في :",
  "read-more": "اقرأ أكثر",
  "delete-comment": "حذف التعليق",
  "free-register": "سجّل مجّانًا",
  "view-all": "عرض الكل",
  "placement": "تحديد مستوى",
  "yaqees-blog": "مدونة يقيس",
  "why-student": "لماذا يحب الطلبة",
  "yaqees": "يقيس",
  "student-name": "علي عبد الهادي - طالب ثانوية عامة",
  "student-word":
      "“ قدرت احضر نفسي كويس جدا قبل امتحان الترم حليت اكتر من 20 تدريب في كل المواد والامتحان مخرجش منهم والحمد لله حققت الدرجات النهائية في أغلب المواد .. شكرا يقيس”",
  "FAQs": "أسئلة متكررة",
  "What-platform": "ما هي منصة يقيس؟",
  "yaqees-beneift": "ماذا سوف أستفيد عند الاشتراك في منصة يقيس؟",
  "free-subscribe": "هل الاشتراك مجاني؟",
  "yaqees-source": "ما هو مصدر اختبارات يقيس؟",
  "level-analysis": "كيف يقوم يقيس بتحليل مستوى المتعلم؟",
  "print": "طباعة",
  "appTitle": "نموذج",
  "lang": "اللغة",
  "theme": "المظهر",
  "light": "الوضع المشرق",
  "dark": "الوضع الداكن",
  "system": "حسب النظام",
  "en": "En",
  "ar": "Ar",
  "click": "اضغط",
  "enterEmail": "أدخل البريد الإلكتروني",
  "enterPassword": "أدخل كلمة المرور",
  "enterConfirmPassword": "أدخل تأكيد كلمة المرور",
  "username": "اسم المستخدم",
  "enterUsername": " أدخل اسم المستخدم",
  "login_now": "دخول",
  "no_connection": "يبدو انه ليس لديك اتصال بالإنترنت",
  "try_later": "حدث خطأ ما حاول مرة اخرى لاحقا",
  "location_denaid": "تم رفض اذن الوصول للموقع!",
  "location_denaid_permanently":
      "أذونات الموقع مرفوضة بشكل دائم \n ولا يمكننا طلب أذونات.",
  "location_disabled": "خدمات الموقع معطلة.",
  "try_again": "حاول مجددا",
  "full_name": "الأسم",
  "phone_number": "رقم الهاتف",
  "email": "البريد الألكتروني",
  "password": "كلمة المرور",
  "forget_password": "هل نسيت كلمة السر؟",
  "app_welcom": "أهلا بك في تطبيق مشكاة الاحاديث",
  "app_name": "مشكاة الاحاديث",
  "Login_now": "قم بتسجيل الدخول للاستمرار في رحلتك العلمية",
  "register_now": "سجل الآن وابدا رحلتك مع مشكاة الاحاديث",
  "regNow": "سجل الآن",
  "dont_have_acc": "ليس لديك حساب؟ ",
  "e-mailVerification": "تـأكيد البريد الإلكتروني",
  "email_Verification": "رمز تنشيط الحساب",
  "sign_up": "إنضم الينا",
  "create_account": "انشاء حساب",
  "already_have_an_account": "لديك حساب ؟ ",
  "register": "إنشاء حساب",
  "phone": "رقم الموبايل",
  "signin": "تسجيل الدخول",
  "forgot": "نسيت كلمة المرور",
  "lablePhone": "البريد الإلكتروني أو رقم الهاتف",
  "or": "or",
  "google": "تسجيل الدخول بحساب Google",
  "enterTax": "%أدخل السعر شامل الضريبة ۱٥",
  "loginEmail": "تسجيل الدخول بالبريد الإلكتروني",
  "loginPhone": "تسجيل الدخول باستخدام الهاتف",
  "apple": "تسجيل الدخول بحساب apple",
  "recover": "إستعادة كلمة المرور",
  "recoverSuccesse": "استعادة النجاح",
  "continue": "تأكيد",
  "recavry_password": "سوف نرسل لك الكود في بريدك الإلكتروني",
  "recoverlable": "عنوان البريد الالكترونى",
  "recovertext": "أدخل عنوان البريد الإلكتروني المسجل لاستعادة كلمة المرور",
  "recoverPassword": "انشاء كلمة المرور الجديده",
  "recovertextSuccesse":
      "تم إرسال بريد إلكتروني يحتوي على رابط لإدخال كلمة المرور الجديدة",
  "newPassword": "كلمة السر الجديدة",
  "newPasswordText":
      "يجب أن تكون كلمة المرور الجديدة مختلفة عن القديمة حتى يكون الحساب أكثر أمانًا",
  "newPasswordLable": "كلمة المرور",
  "newPasswordConfirmLable": "تأكيد كلمة المرور",
  "signup": "حساب جديد",
  "signupName": "الأسم بالكامل",
  "signupPhone": "رقم الهاتف",
  "signupCity": "المدينة (اختياري)",
  "signupEmail": "عنوان البريد الإلكتروني",
  "signupPassword": "كلمة المرور",
  "signupConfirm": "تأكيد كلمة المرور",
  "signupRegister": "سجل الآن ",
  "registerFree": "سجل مجانا ",
  "signupAgree": "انا أوافق مع الشروط والسياسة",
  "verification": "رمز التحقق",
  "veritificationtext": "أدخل رمز المصادقة OTP أدناه",
  "s": "ث",
  "resend": "أعد إرسال الرمز مرة أخرى",
  "search": "ابحث عن حديث...",
  "platforms": "المنصات",
  "categories": "الاقسام",
  "ads": "إعلانات",
  "filter": "فلتـــرة",
  "newPost": "اضف اعلانك الآن ",
  "seeAll": "مشاهدة الكل",
  "playstation": "بلايستيشن",
  "drawerHome": "الرئيسية",
  "drawerProfile": "الملف الشخصي",
  "drawerDashboard": "أختبار",
  "drawerSettings": "الأعدادت",
  "drawerExams": "الإختبارت",
  "drawerBlog": "المدونة",
  "more": "المزيد",
  "title-slider1": "الأحاديث النبوية الصحيحة",
  "title-slider2": "الاطلاع علي مدي صحة الحديث",
  "title-slider3": "الاطلاع علي شرح الحديث بايجاز",
  "drawerOrders": "طلباتي",
  "drawerFavorites": "المفضلة",
  "drawerCard": "عربة التسوق",
  "drawerMessages": "رسائل",
  "drawerAds": "إعلاناتي",
  "drawerContact": "اتصل بنا",
  "drawerHelp": "مساعدة",
  "drawerTerms&Condition": "الشروط والأحكام",
  "drawerRegisterTrader": "سجل كتاجر",
  "drawerLogOut": "تسجيل خروج",
  "logOut": "خروج",
  "lg": "EN",
  "personal_Information": "المعلومات الشخصية",
  "edit": "تعديل",
  "privacy_setting": "إعدادات الخصوصية",
  "change_password": "تغير كلمة السر",
  "avatars": "اڤاتار",
  "IBAN": "رقم الآيبان",
  "favorite": "مفضلة",
  "chat": "اسأل",
  "price": "السعر",
  "published": "تم النشر",
  "buy": "شراء",
  "games": "Games",
  "all": "الكل",
  "x-box": "اكس بوكس",
  "pc": "الحاسوب",
  "chatTextInput": "اطلب شيئًا هنا.",
  "newAd": "إعلان جديد",
  "itemName": "اسم العنصر",
  "coverPhoto": "تحميل صورة الغلاف",
  "currentLocation": "الموقع الحالي",
  "quantity": "QTY",
  "weight": "وزن",
  "phoneNumber": "رقم الجوال",
  "description": "التفاصيل",
  "uploadPhoto": "تحميل صورة",
  "only8Photos": "يمكنك فقط إضافة ما يصل إلى 6 صور",
  "sendHand": "تسليم باليد",
  "sendComant": "أرسل مع شركة الشحن",
  "iAgreeWith": "انا أوافق مع ",
  "termsAndConditions": "الأحكام والشروط",
  "save": "حفظ",
  "post": "نشر",
  "allExams": "كل الإختبارات",
  "choose": "أختار",
  "fullName": "الاسم الكامل",
  "bankName": "اسم البنك",
  "changeAvatar": "تغيير الصورة الرمزية الخاصة بك؟",
  "yes": "نعم",
  "no": "لا",
  "wallet": "محفظتي",
  "yourProfit": "الرصيد المتاح",
  "receiveTheAmount": "سوف تتلقى المبلغ عند بيع الطلب",
  "numberOfOrders": "عدد الطلبات",
  "numberReceived": "تم استلام",
  "inProgress": "قيد التقدم",
  "completed": "مكتمل",
  "canceled": "ألغيت",
  "orderId": "رقم الطلب",
  "confirmReceiving": "تأكيد الاستلام",
  "chatWithTheBuyer": "تحدث مع البائع",
  "details": "تفاصيل",
  "rateOrder": "قيم الطلب",
  "done": "حسناً",
  "ok": "حسناً",
  "confirmNewPass": "تأكيد",
  "VAT": "ضريبة القيمة المضافة: ",
  "paymentMethod": "طريقة الدفع : ",
  "deliveryMethod": "طريقة التوصيل: ",
  "orderDiscount": "نسبة التخفيض: ",
  "deliveryDate": "موعد التسليم: ",
  "personalPromoCode": "رمز ترويجي شخصي",
  "tybeSomethingHere": "اكتب شيئًا ما هنا",
  "ordersDetails": "تفاصيل الطلب",
  "gamersStore": "حول هذه اللعبة",
  "productDeliveryOptions": "خيارات تسليم المنتج",
  "year": "سنين",
  "yearOne": "منذ سنة",
  "yearTow": "منذ سنتين",
  "month": "اشهر",
  "monthOne": "منذ شهر",
  "monthTow": "منذ شهرين",
  "weeks": "اسابيع",
  "weeksOne": "منذ أسبوع",
  "weeksTwo": "منذ أسبوعين",
  "today": "اليوم",
  "hours": "ساعات",
  "minutes": "دقائق",
  "day": "أيام",
  "SendMessage": "ارسل رسالة",
  "Send request": "إرسال الطلب",
  "customerRating": "تقييم العملاء",
  "paymentMethodShipping": "طريقة الدفع او السداد",
  "orderReview": "مراجعة الطلب",
  "discountCodes": "كود خصم",
  "billingSummary": "ملخص الفوترة",
  "cardNumber": "رقم البطاقة",
  "ZipCode": "الرمز البريدي",
  "cardSecurityCode": "رمز أمان البطاقة",
  "paymentSecurity":
      "نحن نحمي معلومات الدفع الخاصة بك باستخدام التشفير لتوفير الأمان على مستوى البنك.",
  "whatThis": "ما هذا؟",
  "itemsCard": "عناصر في البطاقة",
  "validationCode": "أدخل الرمز الذي تم إرساله إلي ",
  "correctCode": "من فضلك قم بإدخال رمز التفعيل صحيحاً .",
  "fillAllCode": "** من فضلك قم باكمال إدخال رمز التفعيل في الحقول .",
  "EnterCouponCode": "أدخل رمز القسيمة الخاص بك",
  "subtotal": "المجموع الفرعي",
  "discount": "تخفيض",
  "shipping": "شحن",
  "tax": "ضريبة",
  "pleaseCheckL": " الخاصة بنا",
  "securityCheckout": "الدفع الآمن",
  "shippingInformation": "معلومات الشحن",
  "receivingMethod": "طريقة الاستلام",
  "deliveryMethodShipping": "طريقة التوصيل",
  "region": "منطقة",
  "city": "مدينة",
  "neighborhood": "حيّ",
  "street": "شارع",
  "buildingNumber": "رقم المبنى",
  "maximumQuantity": "عذرا ، لقد وصلت إلى الحد الأقصى للكمية",
  "disc": "خصم",
  "name": "الاسم",
  "confirmAddress": "تأكيد العنوان",
  "addNewAddress": "أضف عنوان جديد",
  "Home": "العنوان الأساسي",
  "itemInformation": "معلومات المنتج",
  "length": "طول",
  "width": "العرض",
  "height": "ارتفاع",
  "otherDetails": "تفاصيل أخرى",
  "qty": "الكمية",
  "submitProfitRequest": "طلب تحويل الأرباح",
  "profit": "تحويل",
  "confirmation": "تأكيد",
  "errors": "خطأ",
  "You don't have any profits already to transfer":
      "لايوجد لديك ارباح بالفعل لتحويلها",
  "doSubmitProfitRequest": "هل تريد تقديم طلب ربح",
  "submitRequest": "تقديم طلب",
  "shippingInformtion": "معلومات الشحن",
  "district": "حي",
  "postalCode": "رمز بريدي",
  "emailAddress": "عنوان البريد الالكترونى",
  "getInTouch": "أحب أن أسمع منك ، تواصل معنا 👋🏻",
  "send": "إرسال",
  "myAds": "إعلاناتي",
  "active": "نشط",
  "inactive": "غير نشط",
  "sold": "تم البيع",
  "myAdscanceled": "ملغي",
  "proofTransaction": "الإيصال",
  "validName": "أدخل اسمًا صالحًا",
  "validMessage": "أدخل رسالة صالحة ، أكثر من 8 أحرف",
  "validEmail": "أدخل بريدًا إلكترونيًا صالحًا",
  "two-syllableName": "أدخل اسمًا صالحًا من مقطعين",
  "couldNotSend": "آسف - ، الرسالة لم يتم إرسالها",
  "thankContacting": "شكرا - على تواصلك معنا",
  "privacy&Responsibilities": "سياسية الخصوصية و المسؤوليات",
  "aboutUsContent":
      "نحن موقع (GG) الذي تملكه (Good Game) للتسويق الإلكتروني مؤسسة سعودية بإدارة سعودية كاملة. نحن متخصصون في تسويق وترويج السلع والمنتجات والمعلومات عن الآخرين سواء كان فردًا أو مؤسسة أو شركة ، وتتخصص المؤسسة في كل ما يتعلق بالألعاب الإلكترونية سواء كانت أجهزة أو منتجات أو معلومات أو قطع غيار ، وأن يسمح موقع (GG) للمستخدم سواء كان فردًا أو مؤسسة أو شركة ، بعرض منتجاته من خلال إنشاء إعلان على الموقع ، كما يسمح للمستخدم سواء كان فردًا أو مؤسسة أو شركة بشراء أي منتج تم الإعلان عنه من خلال المستخدمين بما لا يتعارض مع قواعد وسياسات استخدام الموقع.",
  "installmentService": "خدمة التقسيط من",
  "expiryDate": "تاريخ انتهاء",
  "validPassword": "كلمة المرور لا تقل عن 6 أحرف.",
  "validConfirmPassword": "تأكيد كلمة المرور لا تتطابق مع كلمة المرور",
  "validPhone": "أدخل رقم هاتف صالحًا",
  "\$": "ر.س",
  "purchaseOrder": "طلب شراء",
  "buyerInformation": "معلومات المشتري",
  "address": "العنوان",
  "paymentStatus": "حالة السداد",
  "paid": "تم الدفع",
  "sentConfirmation": "تأكيد تسليم العنصر",
  "selectLocation": "حدد موقع الاستلام",
  "myAdsShipping": "توصيل",
  "updateAdHite": "هل تريد تحديث الإعلان؟",
  "deleteAd": "حذف الإعلان؟",
  "deleteAdHite": "هل تريد حذف الإعلان بشكل نهائي ام إخفائه مؤقتاً",
  "saveAd": "حفظ الإعلان؟",
  "reliability": "موثوقية المصادر",
  "reliabilityDes": "جميع الأحاديث مصنفة ومراجعة من مصادر موثوقة",
  "purposefulLearning": "تعلم هادف",
  "purposefulDes": "منهجية تعليمية متكاملة لفهم السنة النبوية",
  "EaseOfUse": "سهولة الاستخدام",
  "EaseOfUseDes": "واجهة بديهية وسلسة للتصفح والبحث",
  "TrackLearning": "تتبع التعلم",
  "TrackLearningDes": "أدوات متقدمة لتتبع إنجازاتك وتقدمك",
  "saveAdHite": "هل تريد حفظ الإعلان؟",
  "hide": "اخفاء",
  "exploreNow": "استكشف الان",
  "checkNetwork": "يرجى التحقق من إتصالك بالإنترنت",
  "failedLoad": "هناك خطأ ما",
  "tryِAgain": "حاول مرة اخرى",
  "newMessage": "رسالة جديدة",
  "image": "صورة",
  "location": "موقع",
  "update": "تحديث",
  "select": "اختار",
  "addAddres": "أضف العنوان",
  "cm": "سم",
  "kg": "كلغ",
  "removeCart": "إزالة الإعلان من عربة التسوق",
  "removeCartHint": "هل أنت متأكد من إزالة الإعلان من عربة التسوق",
  "publishOrJust": "هل تريد نشر الإعلان ام فقط حفظ التعديل؟",
  "publish": "نشر",
  "welcome": "مرحباً !",
  "cardholder": "إسم صاحب البطاقة",
  "wrong-password": "كلمة المرور غير صالحة للبريد الإلكتروني المحدد",
  "invalid-email": "عنوان البريد الإلكتروني غير صالح.",
  "user-not-found": "لا يوجد مستخدم مطابق للبريد الإلكتروني المحدد.",
  "user-disabled": "تم تعطيل المستخدم المطابق للبريد الإلكتروني المحدد.",
  "email-already-in-use": "يوجد بالفعل حساب بعنوان البريد الإلكتروني المحدد.",
  "operation-not-allowed":
      "لم يتم تمكين حسابات البريد الإلكتروني / كلمة المرور.",
  "weak-password": "كلمة المرور ليست قوية بما فيه الكفاية.",
  "account-exists-with-different-credential":
      "حدث خطأ ، يرجى المحاولة مرة أخرى",
  "invalid-verification-code": "رمز التحقق الخاص ببيانات الاعتماد غير صالح.",
  "invalid-verification-id": "رمز التحقق الخاص ببيانات الاعتماد غير صالح.",
  "invalid-credential": "حدث خطأ ، يرجى المحاولة مرة أخرى",
  "expired-action-code": "تنتهي صلاحية رابط OTP في البريد الإلكتروني.",
  "FirebaseException": "خطأ في الشبكة! تحقق من الاتصال بالإنترنت.",
  "ERROR_USER_NOT_FOUND": "لم يتم العثور على المستخدم!",
  "ERROR_TOO_MANY_REQUESTS": "طلبات كثيرة جدا!",
  "ERROR_INVALID_EMAIL": "بريد إلكتروني خاطئ!",
  "ERROR_OPERATION_NOT_ALLOWED": "العملية غير مسموح بها",
  "requires-recent-login":
      "هذه العملية حساسة وتتطلب مصادقة حديثة. قم بتسجيل الدخول مرة أخرى قبل إعادة محاولة هذا الطلب.",
  "DEFAULT": "حدث خطأ ، يرجى المحاولة مرة أخرى",
  "successConfirm": "تهانينا!",
  "lableConfirm": ". سيتم توصيل طلبك قريبًا\n! شكرا لاختيارك تطبيقنا",
  "seeOrder": "مشاهدة  طلباتي",
  "availabilityCode": "ادخل كود الإتاحة",
  "enterDiscountCode": "ادخل كود الخصم",
  "discountCode": "كود الخصم",
  "goHomePage": "انتقال إلى الصفحة الرئيسية",
  "goCatePage": "انتقال إلى كل الاقسام",
  "AdNotAvailable": "عذرا ، الإعلان غير متوفر الآن",
  "ad": "الإعلان",
  "account-activation": "تفعيل الحساب",
  "quantityAvailable": "الكمية متاحة:",
  "numberAlreadyRegistered": "رقم الهاتف مسجل بالفعل",
  "completeProfile": "إكمال الملف الشخصي",
  "settings": "الإعدادات",
  "completeProfileContect":
      "الرجاء إضافة رقم الجوال و الإيميل في الملف الشخصي اولاً",
  "profilePersonly": "الملف الشخصي",
  "tryAgane": "محاولة مرة أخرى",
  "completeAddress": "يرجى استكمال معلومات العنوان",
  "productBeenSent": "هل تم إرسال المنتج؟",
  "locationNotSpecified": "الموقع غير محدد",
  "downloadComplete": "تم التحميل",
  "unableApple": "غير قادر على الاتصال بحساب آبل",
  "unableGoogle": "تعذر الاتصال بحساب Google",
  "emailRequirement": "البريد الإلكتروني هو الشرط",
  "error": "هناك شيء خاطئ ، حاول مرة أخرى",
  "unavailable": "الخدمة غير متوفرة حاليا. يرجى المحاولة مرة أخرى في وقت لاحق.",
  "unknown": "حدث خطأ غير معروف. يرجى التحقق من استجابة الخادم.",
  "loginAccount": "تسجيل الدخول",
  "recover_password": "استعادة كلمة السر",
  "signInFirst": "تحتاج إلى تسجيل الدخول أولا",
  "login/register": "يرجى تسجيل الدخول / أنشاء حساب جديد أولاً لإجراء معاملة",
  "loginFirst": "يجب تسجيل الدخول اولا",
  "loginEnter": "دخول",
  "enterCode": "أدخل الرمز المرسل الي ",
  "sendVerification": "تحقق",
  "remove": "إزالة",
  "password_validator1": "الرجاء إدخال كلمة المرور الخاصة بك.",
  "password_validator2": "يجب أن تتكون كلمة المرور من 6 أرقام على الأقل",
  "name_validator1": "الرجاء إدخال الاسم الخاصة بك.",
  "name_validator2": "يجب أن يتكون الأسم من 6 حروف على الأقل",
  "email_validator1": "الرجاء إدخال الإيميل الخاصة بك.",
};
