name: Flutter CI/CD

on:
  push:
    branches: [ "main", "v5", "v5" , "master"]
  pull_request:
    branches: [ "main", "v5", "v5" , "master"]

jobs:
  analyze_and_test:
    name: Analyze and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'
          channel: 'stable'
          cache: true # Enable caching for Flutter packages

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Analyze code
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Run tests with coverage
        run: flutter test --coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v5
        with:
          name: coverage-report
          path: coverage/lcov.info

  build_android:
    name: Build Android
    needs: analyze_and_test # This job will only run if analyze_and_test passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'
          channel: 'stable'
          cache: true # Uses the cached packages from the previous job

      - name: Install dependencies
        run: flutter pub get


      - name: Code generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Android APK
        run: flutter build apk --release

      - name: Build Android App Bundle (AAB)
        run: flutter build appbundle --release

      - name: Upload Android APK artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Upload Android AAB artifact
        uses: actions/upload-artifact@v5
        with:
          name: app-release-aab
          path: build/app/outputs/bundle/release/app-release.aab

  build_web:
    name: Build Web
    needs: analyze_and_test # This job will only run if analyze_and_test passes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.x'
          channel: 'stable'
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Code generation
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Build Web
        run: flutter build web --release

      - name: Upload Web artifact
        uses: actions/upload-artifact@v5
        with:
          name: web-build
          path: build/web
